{
    "error":"${error}",
    "exceed": "${exceed}",
    "EXCEEDED_VND": "<fmt:formatNumber value="${EXCEEDED_VND}" pattern="###,###.##"/>",
    "EXCEEDED_USD":"<fmt:formatNumber value="${EXCEEDED_USD}" pattern="###,###.##"/>",
    "RECIPIENT_PAYMENT_USD": "<fmt:formatNumber value="${RECIPIENT_PAYMENT_USD}" pattern="###,###.##"/>",
    "RECIPIENT_PAYMENT_VND": "<fmt:formatNumber value="${RECIPIENT_PAYMENT_VND}" pattern="###,###.##"/>",
    "CURRENT_PAYMENT_USD": "<fmt:formatNumber value="${CURRENT_PAYMENT_USD}" pattern="###,###.##"/>",
    "CURRENT_PAYMENT_VND": "<fmt:formatNumber value="${CURRENT_PAYMENT_VND}" pattern="###,###.##"/>",
    "SELECTED_PRODUCT_ID": "${SELECTED_PRODUCT_ID}",
    "SELECTED_PRODUCT_QUANTITY": "${SELECTED_PRODUCT_QUANTITY}",
    "LIXI_GIFT_PRICE" : "<fmt:formatNumber value="${LIXI_GIFT_PRICE}" pattern="###,###.##"/>",
    "LIXI_GIFT_PRICE_VND" : "<fmt:formatNumber value="${LIXI_GIFT_PRICE_VND}" pattern="###,###.##"/>",
    "LIXI_FINAL_TOTAL" : "<fmt:formatNumber value="${LIXI_FINAL_TOTAL}" pattern="###,###.##"/>",
    "LIXI_FINAL_TOTAL_VND" : "<fmt:formatNumber value="${LIXI_FINAL_TOTAL_VND}" pattern="###,###.##"/>",
    "LIXI_HANDLING_FEE" : "<fmt:formatNumber value="${LIXI_HANDLING_FEE}" pattern="###,###.##"/>",
    "LIXI_HANDLING_FEE_TOTAL" : "<fmt:formatNumber value="${LIXI_HANDLING_FEE_TOTAL}" pattern="###,###.##"/>",
    "CARD_PROCESSING_FEE_THIRD_PARTY" : "<fmt:formatNumber value="${CARD_PROCESSING_FEE_THIRD_PARTY}" pattern="###,###.##"/>",
    "message":"<spring:message code="validate.exceeded"><spring:argument value="${EXCEEDED_VND}"/><spring:argument value="${EXCEEDED_USD}"/></spring:message>"
}